version: 2
jobs:
   build:
     docker:
       - image: surenwork/ngk-boilerplate:0.1.7
     working_directory: ~/source
     steps:
       - checkout
       - restore_cache:
           key: dependency-cache-{{ checksum "package.json" }}
       - run:
           name: Install npm wee
           command: npm install
       - save_cache:
           key: dependency-cache-{{ checksum "package.json" }}
           paths:
             - node_modules
       - run:
           name: Build the Application
           command: npm run build
   deploy:
     docker:
       - image: surenwork/ngk-boilerplate:0.1.7
     working_directory: ~/source
     steps:
       - checkout
       - setup_remote_docker:   # (2)
          docker_layer_caching: true # (3)
       - run: echo "hello world"
       - run: ls -la ~/source
       - run:
          name: Setting Up Google Cloud Environment
          command: |
            echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
            sed -i 's/\r$//' ~/setup_gcloud.sh
            bash ~/setup_gcloud.sh
       - run:
          name: Test kubectl commands
          command: |
            kubectl get nodes
            kubectl config current-context
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
