version: 2
jobs:
   build:
     docker:
       - image: surenwork/ngk-boilerplate:0.1.6
     working_directory: ~/source
     steps:
       - checkout
       - setup_remote_docker:   # (2)
          docker_layer_caching: true # (3)
       - run: echo "hello world"
       - run: ls -la ~/
       - run: echo "Setting up Google cloud"
